-- auto Generated on 2017-10-18 11:14:22 
-- DROP TABLE IF EXISTS `demo`; 
CREATE TABLE demo(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `age` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'age',
    `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'name',
    `email` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'email',
    `test` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'test',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'demo';
