package com.maple.fastweb.mybatis.model;

import com.maple.fastweb.base.po.Table;

public class Commonlog extends Table{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commonlog.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commonlog.updatetime
     *
     * @mbggenerated
     */
    private Long updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commonlog.logcontent
     *
     * @mbggenerated
     */
    private String logcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commonlog.id
     *
     * @return the value of commonlog.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commonlog.id
     *
     * @param id the value for commonlog.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commonlog.updatetime
     *
     * @return the value of commonlog.updatetime
     *
     * @mbggenerated
     */
    public Long getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commonlog.updatetime
     *
     * @param updatetime the value for commonlog.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Long updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commonlog.logcontent
     *
     * @return the value of commonlog.logcontent
     *
     * @mbggenerated
     */
    public String getLogcontent() {
        return logcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commonlog.logcontent
     *
     * @param logcontent the value for commonlog.logcontent
     *
     * @mbggenerated
     */
    public void setLogcontent(String logcontent) {
        this.logcontent = logcontent == null ? null : logcontent.trim();
    }

    public Commonlog(Long id, Long updatetime, String logcontent) {
        this.id = id;
        this.updatetime = updatetime;
        this.logcontent = logcontent;
    }

    public Commonlog() {
    }
}