package com.maple.fastweb.mybatis.mapper;

import com.maple.fastweb.base.mapper.BaseMapper;
import com.maple.fastweb.mybatis.model.Commonlog;

public interface CommonlogMapper extends BaseMapper<Long,Commonlog>{
   /* *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlog
     *
     * @mbggenerated
     *//*
    int deleteByPrimaryKey(Long id);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlog
     *
     * @mbggenerated
     *//*
    int insert(Commonlog record);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlog
     *
     * @mbggenerated
     *//*
    int insertSelective(Commonlog record);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlog
     *
     * @mbggenerated
     *//*
    Commonlog selectByPrimaryKey(Long id);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlog
     *
     * @mbggenerated
     *//*
    int updateByPrimaryKeySelective(Commonlog record);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlog
     *
     * @mbggenerated
     *//*
    int updateByPrimaryKeyWithBLOBs(Commonlog record);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlog
     *
     * @mbggenerated
     *//*
    int updateByPrimaryKey(Commonlog record);*/
}