package com.maple.fastweb.mybatis.mapper;

import com.maple.fastweb.base.mapper.BaseMapper;
import com.maple.fastweb.mybatis.model.User;

public interface UserMapper extends BaseMapper<Long,User>{
   /* *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     *//*
    int deleteByPrimaryKey(Long id);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     *//*
    int insert(User record);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     *//*
    int insertSelective(User record);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     *//*
    User selectByPrimaryKey(Long id);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     *//*
    int updateByPrimaryKeySelective(User record);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     *//*
    int updateByPrimaryKey(User record);*/
}